# Generated by Django 3.2.5 on 2023-07-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('dinero', models.IntegerField()),
            ],
        ),
    ]
