# Generated by Django 3.2.5 on 2023-07-03 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_cuentacorriente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorriente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahorros', to=settings.AUTH_USER_MODEL),
        ),
    ]
