# Generated by Django 3.2.5 on 2023-07-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20230706_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='prestamo',
            field=models.IntegerField(default=10000),
        ),
    ]
